spring.application.name=cs341-demo
spring.datasource.url=jdbc:mysql://localhost/game_tracker
spring.datasource.username = gt_app
spring.datasource.password = Max12
spring.jpa.hibernate.ddl-auto=update